In [1]:
import numpy as np

# DataTypes & Attributes

In [2]:
# Numpy's Main Datatypre is ND-Array
a1 =  np.array([1,2,3])
a1


array([1, 2, 3])

In [3]:
type(a1)

numpy.ndarray

In [4]:
a2 = np.array([[1,2,3],[1,2,3]])
a2

array([[1, 2, 3],
       [1, 2, 3]])

In [5]:
a3 = np.array([[[1,2,3],[3,4,5],[6,7,8]],[[9,10,11],[12,13,14],[15,16,17]]])
a3

array([[[ 1,  2,  3],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]]])

In [6]:
a3.shape, a2.shape

((2, 3, 3), (2, 3))

In [7]:
a1.ndim,a2.ndim,a3.ndim

(1, 2, 3)

# Creating numpy array

In [8]:
samole_array = np.array([1,2,3])
samole_array

array([1, 2, 3])

In [9]:
ones = np.ones((2,3))
ones

array([[1., 1., 1.],
       [1., 1., 1.]])

In [10]:
ones.dtype

dtype('float64')

In [11]:
zeroes = np.zeros((2,3))
zeroes

array([[0., 0., 0.],
       [0., 0., 0.]])

In [12]:
range_array = np.arange(0,10,2)
range_array

array([0, 2, 4, 6, 8])

In [13]:
random_array = np.random.randint(0,10,size = (3,5))

In [14]:
random_array

array([[8, 9, 7, 9, 8],
       [1, 9, 8, 4, 3],
       [8, 7, 9, 8, 9]])

# numpy random seed

In [15]:
#  Pseudo-random numbers
np.random.seed(7)
random_array_2 = np.random.rand(3,2)
random_array_2

array([[0.07630829, 0.77991879],
       [0.43840923, 0.72346518],
       [0.97798951, 0.53849587]])

# Viewing arrays and Matrices

In [16]:
rr =np.random.randint(0,20,size = (2,5,3,4))
rr

array([[[[ 8, 14, 10,  8],
         [ 7,  6,  4, 16],
         [ 7, 12,  0, 11]],

        [[ 6, 19, 12,  5],
         [16,  0,  2,  9],
         [14,  6,  4, 14]],

        [[ 9,  3,  3,  8],
         [19, 16,  1,  0],
         [16, 12,  7, 10]],

        [[ 9,  3,  0,  7],
         [ 0,  4,  3,  1],
         [ 3,  1, 19,  4]],

        [[19,  1,  5,  9],
         [17,  2, 19, 18],
         [18,  3, 11, 15]]],


       [[[16, 12, 11,  9],
         [ 9, 12,  3, 14],
         [14, 15,  3, 16]],

        [[ 4, 11,  8, 11],
         [15, 13, 18,  7],
         [ 3, 12, 12, 15]],

        [[ 8,  6,  6, 12],
         [ 7, 17, 10, 15],
         [ 5,  4,  9,  9]],

        [[ 0,  2, 12,  6],
         [ 8,  2, 10, 14],
         [17,  6, 10, 17]],

        [[ 5, 15, 17, 12],
         [ 9,  8, 15,  5],
         [ 9,  4, 12,  9]]]])

In [17]:
rr[1,4,0,:]

array([ 5, 15, 17, 12])

#  4. Manipulating and compring arrays

# arithmetic

In [19]:
a1

array([1, 2, 3])

In [25]:
ones = np.ones(3)
ones

array([1., 1., 1.])

In [22]:
ones.dtype

dtype('float64')

In [26]:
a1+ones

array([2., 3., 4.])

similarly we can perform division, mutiplication

#  Aggregation

aggregation = performing the same operation on a number of things

In [27]:
listy = [1,2,3]
type(listy)

list

In [28]:
listy = np.array(listy)

In [29]:
type(listy)

numpy.ndarray

In [30]:
np.sum(listy)

6

In [31]:
massive_array = np.random.random(1)

In [44]:
%timeit \sum(massive_array)
%timeit np.sum(massive_array)

9.61 ms ± 168 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)
14.8 µs ± 673 ns per loop (mean ± std. dev. of 7 runs, 100,000 loops each)


NameError: name 'p' is not defined

In [49]:
np.mean(massive_array)

100277.42697

In [50]:
np.sum(massive_array)

10027742697

In [51]:
#  Standard deviation = a measure of how spreadout a group of numbers from mean
np.std(massive_array)

160.6517090684662

In [53]:
# Variance = measure of the average degree to which each number is different to mean
# Higher variance = Wider range of numbers
# Lower vaariance = Lower Range of Numbers
np.var(massive_array)

25808.971626619106

# Reshape and Transpose

In [54]:
a2

array([[1, 2, 3],
       [1, 2, 3]])

In [56]:
a2.shape

(2, 3)

In [57]:
a3

array([[[ 1,  2,  3],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]]])

In [58]:
a2*a3

ValueError: operands could not be broadcast together with shapes (2,3) (2,3,3) 

In [63]:
#  need for reshaping
a2.reshape(2,3,1)*a3

array([[[ 1,  2,  3],
        [ 6,  8, 10],
        [18, 21, 24]],

       [[ 9, 10, 11],
        [24, 26, 28],
        [45, 48, 51]]])

In [64]:
# tranpose
a2.T

array([[1, 1],
       [2, 2],
       [3, 3]])

# dot product

In [66]:
np.random.seed(0)
mat1=np.random.randint(10,size = (5,3))
mat2=np.random.randint(10,size = (5,3))
mat1,mat2

(array([[5, 0, 3],
        [3, 7, 9],
        [3, 5, 2],
        [4, 7, 6],
        [8, 8, 1]]),
 array([[6, 7, 7],
        [8, 1, 5],
        [9, 8, 9],
        [4, 3, 0],
        [3, 5, 0]]))

In [68]:
np.dot(mat1,mat2.T)

array([[ 51,  55,  72,  20,  15],
       [130,  76, 164,  33,  44],
       [ 67,  39,  85,  27,  34],
       [115,  69, 146,  37,  47],
       [111,  77, 145,  56,  64]])